# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69988c3e1bc55754fb0e544715d4dc4187b396cee457fca9ab0b0982dc4293b75031abbb6893d189ae05bdf2b6495b2ff2bcd9404f3c73074fb3c2cab9a9a9a0

test:
  secret_key_base: 0bfd56a0d8b0d5e0c69634078c7af15acf865c50ad4e4397ff9e6218eff89a620e07245c9d7864da48ea62ba42913461fb522480ce42fc7176a61f1d11f00ad4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
